### PR TITLE
Ability to add a project to your favorites.

### PR DESCRIPTION
**Pull request by prodex**
issue #13

### CODE REVIEW

**Comment by samdark** [comment]
Thanks for contribution. I've reviewed it and it seems I haven't explained idea enough... Favorites was not about rating projects, it was about actually bookmarking a project and accessing your bookmarks via your profile.

**Comment by samdark** [comment]
What you did is very close to https://github.com/samdark/yiipowered/issues/14.

**Comment by samdark** [comment]
Can't merge the pull request. Sorry.

**Comment by prodex** [comment]
TODO:
1) Ability to add a project to bookmarks
2) In the profile show the list of projects added to the bookmarks

In this case, the bookmarks are private to the user. Right?

**Comment by samdark** [comment]
Yes, they are.

**Pull request closed without merging**
